trigger: none

resources:
  pipelines:
  - pipeline: build
    source: 'demo-az-apim - core - BUILD'
  
variables:
  vmImageName: 'ubuntu-latest'
  azureSubscription: 'Demo Account'
  region: 'East US'

stages:
- template: azure-release-pipelines-stage-template.yml
  parameters:
    stageName: 'CI'
    environment: 'APIM-CI'
    azureSubscription: ${{ variables.azureSubscription }}
    region: ${{ variables.region }}
    resourceGroupName: 'rutzsco-demo-api-management-ci' 
    serviceName: 'rutzsco-demo-api-management-ci'
    publisherName: 'rutzsco'
    publisherEmail: 'scrutz@microsoft.com'
    AADRegistrationName: 'aad'
    AADClientId: $(AADClientId)
    AADClientSecret: $(AADClientSecret)
    AADAuthorizationEndpoint: $(AADAuthorizationEndpoint)
    AADTokenEndpoint: $(AADTokenEndpoint)
- template: azure-release-pipelines-stage-template.yml
  parameters:
    stageName: 'QA'
    environment: 'APIM-QA'
    azureSubscription: ${{ variables.azureSubscription }}
    region: ${{ variables.region }}
    resourceGroupName: 'rutzsco-demo-api-management-qa' 
    serviceName: 'rutzsco-demo-api-management-qa'
    publisherName: 'rutzsco'
    publisherEmail: 'scrutz@microsoft.com'
    AADRegistrationName: 'aad'
    AADClientId: $(AADClientId)
    AADClientSecret: $(AADClientSecret)
    AADAuthorizationEndpoint: $(AADAuthorizationEndpoint)
    AADTokenEndpoint: $(AADTokenEndpoint)
     
