trigger:
  branches:
    include:
    - master
    - main
  paths:
    include:
    - Services/Ingest.Api/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  rootDirectory: 'Services/Ingest.Api'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build project'
  inputs:
    projects: '$(rootDirectory)/**/*.csproj'
    arguments: '--output publish_output --configuration Release'

- task: DotNetCoreCLI@2
  displayName: 'Publish project'
  inputs:
    command: publish
    publishWebProjects: false
    projects: '$(rootDirectory)/**/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'App'
    publishLocation: 'pipeline'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(rootDirectory)/Infrastructure'
    artifact: 'Infrastructure'
    publishLocation: 'pipeline'
