trigger: none

resources:
  pipelines:
  - pipeline: build
    source: 'demo-az-api-management - simulation service - BUILD'
  
variables:
  vmImageName: 'vs2017-win2016'
  azureSubscription: 'Demo Account'
  region: 'East US'
  app-name: 'demo-api-managment-simulation-service'
  storageAccountName: 'azfuncapimssci'
  resourceGroupName: 'demo-api-managment'  

stages:
 - stage: CI
   displayName: CI stage 
    
   jobs:
   - deployment: Deploy
     displayName: Deploy
     environment: 'CI'
     pool:
        vmImage: $(vmImageName)   
      
     strategy:
        runOnce:
          deploy:
  
            steps:
           
            - task: AzureResourceGroupDeployment@2
              displayName: '1. Create Function Infrastructure'
              inputs:
                azureSubscription: '$(azureSubscription)'
                resourceGroupName: '$(resourceGroupName)'
                location: '$(region)'
                csmFile: '$(Pipeline.Workspace)/build/Infrastructure/function-app-consumption.json'
                overrideParameters: '-appName $(app-name) -storageAccountName $(storageAccountName)'
                deploymentOutputs: ResourceGroupDeploymentOutputs

            - task: AzureFunctionApp@1
              displayName: '2. Azure functions app deploy'
              inputs:
                azureSubscription: '$(azureSubscription)'
                appType: functionApp
                appName: $(app-name)
                package: '$(Pipeline.Workspace)/build/App/Simulation.Service.zip'
                AppSettings: ''