trigger: none

resources:
  pipelines:
  - pipeline: build
    source: 'demo-az-api-management - simulation service - BUILD'
  
variables:
  vmImageName: 'windows-latest'
  azureSubscription: 'Demo Account'
  region: 'eastus'
  app-name: 'demo-simulation-service'
  storageAccountName: 'azfuncapimssci'
  resourceGroupName: 'rutzsco-demo-api-management-ci' 
  templateFile: $(Pipeline.Workspace)/build/Infrastructure/main.bicep

stages:
 - stage: CI
   displayName: CI stage 
    
   jobs:
   - deployment: Deploy
     displayName: Deploy
     environment: 'CI'
     pool:
        vmImage: $(vmImageName)   
      
     strategy:
        runOnce:
          deploy:
  
            steps:
            - task: AzureCLI@2
              displayName: '1. Create Function Infrastructure'
              inputs:
                azureSubscription: $(azureSubscription)
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                  az group create --name $(resourceGroupName) --location $(region)
                  az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFile) --parameters functionAppName=$(app-name) functionAppStorageAccountName=$(storageAccountName) > outputs.json

            - task: AzureFunctionApp@1
              displayName: '2. Azure functions app deploy'
              inputs:
                azureSubscription: '$(azureSubscription)'
                appType: functionApp
                appName: $(app-name)
                package: '$(Pipeline.Workspace)/build/App/Simulation.Service.zip'
                AppSettings: '-AuthTenantId $(AuthTenantId) -AuthClientId $(AuthClientId) -AuthClientSecret $(AuthClientSecret) -EndpointUrl $(EndpointUrl) -AuthScope $(AuthScope) -Ocp-Apim-Subscription-Key $(Ocp-Apim-Subscription-Key)'