trigger: none

resources:
  pipelines:
  - pipeline: build
    source: 'demo-az-apim - conference api - BUILD'
  
variables:
  vmImageName: 'vs2017-win2016'
  azureSubscription: 'Demo Account'
  region: 'East US'
  storageAccountName: 'azfuncapimiaci'
  resourceGroupName: 'rutzsco-demo-api-management'  
  apimServiceName: 'rutzsco-demo-api-management'
  AADRegistrationName: 'msft-aad'  
stages:
 - stage: CI
   displayName: CI stage 
    
   jobs:
   - deployment: Deploy
     displayName: Deploy
     environment: 'CI'
     pool:
        vmImage: $(vmImageName)   
      
     strategy:
        runOnce:
          deploy:
  
            steps:
           
            - task: AzureResourceGroupDeployment@2
              displayName: '1. Create APIM API'
              inputs:
                azureSubscription: '$(azureSubscription)'
                resourceGroupName: '$(resourceGroupName)'
                location: '$(region)'
                csmFile: '$(Pipeline.Workspace)/build/Infrastructure/api-management-api.json'
                overrideParameters: '-serviceName $(apimServiceName) -authorizationServer $(AADRegistrationName)'
                deploymentOutputs: ResourceGroupDeploymentOutputs